/**
 * Expense Tracker API Contract
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PurchaseItemDto } from './purchaseItemDtoDTO';


export interface PurchaseItemsPage { 
    content: Array<PurchaseItemDto>;
    totalPages: number;
    totalElements: number;
    first: boolean;
    last: boolean;
}

