spring:
  jpa.properties.hibernate:
    generate_statistics: true
    show_sql: true
    format_sql: true
  datasource:
    url: jdbc:postgresql://192.168.101.108:5432/fintracker-dev
    username: postgres
    password: Kawasaki14
