{
 "title": "Expenses",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "selectedCategories",
    "label": "Categories",
    "query": "SELECT DISTINCT CONCAT(pc.name, '|', pc.id)\nFROM purchase pu\nINNER JOIN product pr ON pr.purchase_id = pu.id\nINNER JOIN product_category pc ON pc.id = pr.category_id\nWHERE pu.date BETWEEN '${__from:date:DD-MMM-YYYY}' AND '${__to:date:DD-MMM-YYYY}'"
   },
   {
    "name": "selectedShops",
    "label": "Shops",
    "query": "SELECT DISTINCT CONCAT(ps.name, '|', ps.id)\nFROM purchase pu\nINNER JOIN purchase_shop ps ON ps.id = pu.shop_id\nWHERE pu.date BETWEEN '${__from:date:DD-MMM-YYYY}' AND '${__to:date:DD-MMM-YYYY}'"
   }
  ]
 },
 "panels": [
  { "title": "Categories", "type": "volkovlabs-variable-panel" },
  {
   "title": "Category expenses",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "targets": [
    {
     "rawSql": "select c.name, ROUND(sum(p.amount * p.price)::numeric, 2) as total\nfrom product p\ninner join purchase pg on pg.id = p.purchase_id\ninner join purchase_shop ps on ps.id = pg.shop_id\ninner join product_category c on c.id = p.category_id\nwhere pg.date between '${__from:date:DD-MMM-YYYY}' and '${__to:date:DD-MMM-YYYY}' and ps.id IN ($selectedShops) and c.id IN ($selectedCategories)\ngroup by c.name"
    }
   ]
  },
  { "title": "Shops", "type": "volkovlabs-variable-panel", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 } },
  {
   "title": "Total expenses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ROUND(sum(p.amount * p.price)::numeric, 2) as total\nfrom product p\ninner join purchase pg on pg.id = p.purchase_id\ninner join purchase_shop ps on ps.id = pg.shop_id\ninner join product_category c on c.id = p.category_id\nwhere pg.date between '${__from:date:DD-MMM-YYYY}' and '${__to:date:DD-MMM-YYYY}' and ps.id IN ($selectedShops) and c.id IN ($selectedCategories)"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "targets": [
    {
     "rawSql": "select g.date, s.name, sum( round( cast( (p.price * p.amount) as numeric ) , 2) ) as total\nfrom purchase g\ninner join product p on p.purchase_id = g.id\ninner join purchase_shop s on s.id = g.shop_id\nwhere g.date between '${__from:date:DD-MMM-YYYY}' and '${__to:date:DD-MMM-YYYY}' and s.id IN ($selectedShops)\ngroup by g.id, g.date, s.name\norder by g.date desc, total asc"
    }
   ]
  },
  {
   "title": "Products",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT p.name, p.amount, p.price, round( cast( (p.price * p.amount) as numeric ) , 2) as total\nFROM purchase g\nINNER JOIN product p on p.purchase_id = g.id\nINNER JOIN product_category c on c.id = p.category_id\nINNER JOIN purchase_shop ps on ps.id = g.shop_id\nwhere g.date between '${__from:date:DD-MMM-YYYY}' and '${__to:date:DD-MMM-YYYY}' and ps.id IN ($selectedShops) and c.id IN ($selectedCategories)\n"
    }
   ]
  }
 ]
}