/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package matthias.expense_tracker.openapi.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlin.collections.List
import kotlin.collections.Map

@RequestMapping("\${api.base-path:}")
interface ProductsApi {

    @Operation(
        summary = "Get list of distinct product names",
        operationId = "getProductNames",
        description = "",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "(OK) Success response containing list of distinct product names",
                content = [Content(schema = Schema(implementation = kotlin.String::class))]
            ),
            ApiResponse(
                responseCode = "400",
                description = "(BAD_REQUEST) Failure response when query string is invalid",
                content = [Content(schema = Schema(implementation = kotlin.String::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/api/products/names"],
        produces = ["application/json"]
    )
    fun getProductNames(
        @Parameter(description = "RSQL query string to filter products", required = true) @RequestParam(
            value = "query",
            required = true
        ) query: kotlin.String
    ): ResponseEntity<List<kotlin.String>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
