/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package matthias.expense_tracker.openapi.api

import matthias.expense_tracker.openapi.model.AddShopRequest
import matthias.expense_tracker.openapi.model.ShopDto
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlin.collections.List
import kotlin.collections.Map

@RequestMapping("\${api.base-path:}")
interface ShopsApi {

    @Operation(
        summary = "Add new purchase shop",
        operationId = "addPurchaseShop",
        description = "",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "(OK) Success response containing added purchase shop",
                content = [Content(schema = Schema(implementation = ShopDto::class))]
            ),
            ApiResponse(
                responseCode = "400",
                description = "(BAD_REQUEST) Failure response when request body is invalid",
                content = [Content(schema = Schema(implementation = kotlin.String::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/api/shops"],
        produces = ["application/json"],
        consumes = ["application/json"]
    )
    fun addPurchaseShop(
        @Parameter(
            description = "Request containing new purchase shop to be added",
            required = true
        ) @RequestBody addShopRequest: AddShopRequest
    ): ResponseEntity<ShopDto> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Get list of purchase shops",
        operationId = "getPurchaseShops",
        description = "",
        responses = [
            ApiResponse(
                responseCode = "200",
                description = "(OK) Success response containing list of purchase shops",
                content = [Content(schema = Schema(implementation = ShopDto::class))]
            )
        ]
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/api/shops"],
        produces = ["application/json"]
    )
    fun getPurchaseShops(): ResponseEntity<List<ShopDto>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
