-- CLEANUP SHOPS --
TRUNCATE TABLE purchase_shop CASCADE;

-- CLEANUP CATEGORIES --
TRUNCATE TABLE product_category CASCADE;

-- CLEANUP PURCHASES --
TRUNCATE TABLE purchase CASCADE;

-- CLEANUP PRODUCTS --
TRUNCATE TABLE product CASCADE;
